Repository upbound/build, pull requests merged in 2022-10, with the labels that each got.

#205 fix:(helm): Set HELM_*_HOME env vars to avoid side effects with go
  makelib/helm.mk
Labels: size/S

#209 common: add PLATFORM and VERSION to buildvars
  makelib/common.mk
Labels: size/XS

#210 common: adopt make 4 changes around how to define space
  makelib/common.mk
Labels: size/XS

#212 common: calculate major, minor and patch versions correctly
  makelib/common.mk
Labels: size/S

#213 Enhance docs local development capabilities
  makelib/docs.mk
Labels: size/S

#214 Add uptest tool
  makelib/k8s_tools.mk
Labels: size/S

#208 Add targets to deploy a locally build configuration package
  makelib/controlplane.mk
  makelib/k8s_tools.mk
  makelib/local.xpkg.mk
Labels: size/M

#215 Add control plane dump target
  makelib/controlplane.mk
Labels: size/XS

#216 Dump Crossplane resources as well
  makelib/controlplane.mk
Labels: size/XS
