Repository upbound/build, pull requests merged in 2022-07, with the labels that each got.

#192 fix: Fallback to sha256sum if shasum is not available
  makelib/image.mk
  makelib/imagelight.mk
Labels: size/S

#193 Stop hardcoding `SAFEHOSTARCH` to `amd64` on darwin
  makelib/common.mk
  makelib/k8s_tools.mk
Labels: size/S

#194 Update `golangci-lint` to `1.47.1`
  makelib/golang.mk
Labels: size/XS

#195 Go: Clamp down minimum required version to 1.18
  cross/Dockerfile
  makelib/golang.mk
Labels: size/M

#196 Go: miscellaneous cleanup
  makelib/golang.mk
  makelib/local.mk
  run
Labels: size/L

#197 Fix kustomize patch target regex
  scripts/localdev-prepare.sh
Labels: size/XS

#198 Istio and helm v2 should not be a requirement for local dev
  makelib/local.mk
Labels: size/XS
